version: "3.9"

services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cmderma
      MYSQL_USER: cmderma
      MYSQL_PASSWORD: cmderma
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: rrebelo/cmderma-backend:1339
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cmderma?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: cmderma
      SPRING_DATASOURCE_PASSWORD: cmderma
      APP_ACCESS_CODE: ${APP_ACCESS_CODE:-1234}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8080"

  frontend:
    image: rrebelo/cmderma-frontend:1339
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:443"
    depends_on:
      - backend

volumes:
  mysql-data:
