const FALLBACK_FRONTEND_VERSION = 'dev';
const FALLBACK_BACKEND_VERSION = 'desconhecido';

export const FRONTEND_VERSION = import.meta.env.VITE_FRONTEND_VERSION ?? FALLBACK_FRONTEND_VERSION;
export const BACKEND_VERSION = import.meta.env.VITE_BACKEND_VERSION ?? FALLBACK_BACKEND_VERSION;

